name: Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example

    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.17.0
        with:
          channel: "stable"
      - name: Pub get
        run: flutter pub get
      - name: Build
        run: flutter build web --base-href /${{ github.event.repository.name }}/ --release
      - uses: actions/upload-pages-artifact@v3
        with:
          path: example/build/web

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
